name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: aimharder-bot-496010
  REGION: europe-west1
  REPOSITORY: docker-repo
  IMAGE: aimharder-bot

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/aimharder-bot-496010/docker-repo/aimharder-bot:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push europe-west1-docker.pkg.dev/aimharder-bot-496010/docker-repo/aimharder-bot:${{ github.sha }}

      - name: Tag as latest
        run: |
          docker tag \
            europe-west1-docker.pkg.dev/aimharder-bot-496010/docker-repo/aimharder-bot:${{ github.sha }} \
            europe-west1-docker.pkg.dev/aimharder-bot-496010/docker-repo/aimharder-bot:latest
          docker push europe-west1-docker.pkg.dev/aimharder-bot-496010/docker-repo/aimharder-bot:latest